services:
  indicadores-chile:
    build:
      context: .
      target: production
    container_name: indicadores-chile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '3000:3000'
    networks:
      - internal-net
    environment:
      - NODE_ENV=production

networks:
  internal-net:
    driver: bridge
