name: Build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: Lints
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.15'

      - name: Enable Corepack and Yarn 4.4.0
        run: |
          corepack enable
          corepack prepare yarn@4.4.0 --activate

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run lint
        run: yarn lint

  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.15'

      - name: Enable Corepack and Yarn 4.4.0
        run: |
          corepack enable
          corepack prepare yarn@4.4.0 --activate

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run tests
        run: yarn test

      - name: Prepare coverage report for SonarQube
        run: |
          mv coverage/lcov-report coverage/sonar
          mv coverage/lcov.info coverage/sonar/lcov.info

  sonarcloud:
    name: Sonar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Enable Corepack
        run: |
          corepack enable
          corepack prepare yarn@4.4.0 --activate

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run tests and collect coverage
        run: yarn test --coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v3
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_KEY_IC }}
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.sources=.
            -Dsonar.host.url=https://sonarcloud.io
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_IC }}
